//
// Created by Gianni on 21/12/2023.
//

#ifndef SPACEINVADERS_STATE_IDENTIFIERS_HPP
#define SPACEINVADERS_STATE_IDENTIFIERS_HPP

enum class StateID
{
    MENU,
    SETTINGS,
    GAME,
    PAUSE,
    GAME_OVER,
    HIGH_SCORES,
    KEY_BINDING_STATE,
    TEXT_INPUT_STATE,
    NONE
};

#endif //SPACEINVADERS_STATE_IDENTIFIERS_HPP
